"""init

Revision ID: 142f8afd69d7
Revises: 
Create Date: 2023-10-01 13:28:06.127245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142f8afd69d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('origin', sa.Enum('Facebook', 'Instagram', 'Whatsapp', 'Google', 'Linkedin', 'Outros', name='originleadsenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=11), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('fantasy_name', sa.String(length=50), nullable=True),
    sa.Column('ie', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.Enum('Free', 'Silver', 'Gold', name='plantype'), nullable=True),
    sa.Column('stripe_id', sa.String(length=100), nullable=True),
    sa.Column('data_expire', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=11), nullable=False),
    sa.Column('zip_code', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=50), nullable=True),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('complement', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['core_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('company_type', sa.Enum('Cliente', 'Transportadora', 'Fornecedor', name='companytypeenum'), nullable=False),
    sa.Column('is_individual', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=11), nullable=True),
    sa.Column('last_fantasy_name', sa.String(length=50), nullable=True),
    sa.Column('rg_ie', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['core_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_customizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('changeable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['core_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('directory', sa.String(), nullable=False),
    sa.Column('url_file', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['core_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_form_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['core_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('pix', sa.String(length=100), nullable=True),
    sa.Column('observation', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['core_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['core_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_smtp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('server', sa.String(length=100), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['core_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['core_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('core_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reference_url', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['core_tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('visit_start', sa.DateTime(), nullable=True),
    sa.Column('visit_end', sa.DateTime(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_companies_addresses',
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['core_address.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['core_companies.id'], ondelete='CASCADE')
    )
    op.create_table('core_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('portage_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('form_payment_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('observation', sa.String(length=255), nullable=True),
    sa.Column('url_pdf', sa.String(length=100), nullable=True),
    sa.Column('buyer', sa.String(length=50), nullable=True),
    sa.Column('shipping', sa.Enum('Entrega', 'Retirada', 'Outros', name='shippingenum'), nullable=False),
    sa.Column('status', sa.Enum('Pendente', 'Aprovado', 'Cancelada', name='statusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('contact_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('total_services', sa.Float(), nullable=True),
    sa.Column('total_products', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['core_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_payment_id'], ['core_form_payments.id'], ),
    sa.ForeignKeyConstraint(['portage_id'], ['core_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['core_sellers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['core_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('type_payment', sa.Enum('Pagamento', 'Recebimento', name='paymenttypeenum'), nullable=False),
    sa.Column('status', sa.Enum('Pendente', 'Pago', 'Cancelado', name='paymentreceiptstatusenum'), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('doc_number', sa.String(length=50), nullable=True),
    sa.Column('recipient', sa.String(length=50), nullable=True),
    sa.Column('form_payment_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('installment', sa.Integer(), nullable=False),
    sa.Column('numbers_installments', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('additional_info', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_payment_id'], ['core_form_payments.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['core_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('bar_code', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cost_value', sa.Float(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('minimum_stock', sa.Integer(), nullable=True),
    sa.Column('maximum_stock', sa.Integer(), nullable=True),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('active_pdv', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['core_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['core_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_sellers_addresses',
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['core_address.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['core_sellers.id'], ondelete='CASCADE')
    )
    op.create_table('core_tenants_addresses',
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['core_address.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['core_tenants.id'], ondelete='CASCADE')
    )
    op.create_table('core_tenants_smtp',
    sa.Column('smtp_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['smtp_id'], ['core_smtp.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['core_tenants.id'], ondelete='CASCADE')
    )
    op.create_table('core_users_addresses',
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['core_address.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core_users.id'], ondelete='CASCADE')
    )
    op.create_table('core_history_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('before_stock', sa.Integer(), nullable=False),
    sa.Column('after_stock', sa.Integer(), nullable=False),
    sa.Column('observation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['core_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['core_tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_orders_files',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['core_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['core_orders.id'], ondelete='CASCADE')
    )
    op.create_table('core_orders_products',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['core_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['core_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    op.create_table('core_orders_services',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['core_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['core_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'service_id')
    )
    op.create_table('core_payments_files',
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['core_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['core_payments.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_payments_files')
    op.drop_table('core_orders_services')
    op.drop_table('core_orders_products')
    op.drop_table('core_orders_files')
    op.drop_table('core_history_stock')
    op.drop_table('core_users_addresses')
    op.drop_table('core_tenants_smtp')
    op.drop_table('core_tenants_addresses')
    op.drop_table('core_sellers_addresses')
    op.drop_table('core_products')
    op.drop_table('core_payments')
    op.drop_table('core_orders')
    op.drop_table('core_companies_addresses')
    op.drop_table('core_calendars')
    op.drop_table('core_activity')
    op.drop_table('core_users')
    op.drop_table('core_smtp')
    op.drop_table('core_services')
    op.drop_table('core_sellers')
    op.drop_table('core_form_payments')
    op.drop_table('core_files')
    op.drop_table('core_customizations')
    op.drop_table('core_companies')
    op.drop_table('core_address')
    op.drop_table('core_tenants')
    op.drop_table('core_leads')
    # ### end Alembic commands ###
